### ISSUE TITLE
`if` command does not work with self-defined `function`

### ISSUE THREAD

**Issue by nastevens** [sagiegurari/duckscript#116]
**Describe the bug**
The `if` command doesn't recognize `function`s defined in the code as commands. It appears that `if` only works with built-in/SDK commands.

**To Reproduce**
The following code demonstrates the behavior:
```sh
# The built-in command `set` is called and returns `false` to the `if`,
# so nothing is printed.
if set false
    echo This will not be printed
end

# The custom function is never evaluated. I think `return_bool`
# is being treated as a string and not a command name, and
# since a string is truthy the text is printed.
function return_bool
    echo This will not be printed
    return ${1}
end
if return_bool false
    echo This will be printed
end
```

**Comment by sagiegurari** [comment]
thanks, ya the 'if' command needs more work.
I'll check it.

**Comment by sagiegurari** [comment]
so i checked this one, seems i never intended to support this.
it will be some effort, and i'll think how.
i can explain the technical issue here... but at a high level:
1. conditions (like if) invoke only 1 command.
2. calling a function by name, is actually behind the scenes a goto command to the function start
3. condition ends after the goto, it looks at the result.... there is nothing there (function commands are not invoked, we only invoke 1 command) and its falsy.

**Comment by sagiegurari** [comment]
ok, i think i fixed this one.
so both 'if' and 'not' commands should support it now.
however since its risky change, i'm going to bump the sdk to 0.6 (the duckscript runtime still 0.5, it rarely gets changed).
going to investigate one more thing, but you can install duckscript from the 0.6 branch and try it and give me some feedback.

if you need it for cargo-make, since its a bump from 0.5 to 0.6 you will have to wait a bit longer, as i'll have to update cargo-make for it as well.

thanks a lot for opening the issue and for the vim plugin :)

**Comment by sagiegurari** [comment]
fixed and published.

**Comment by nastevens** [comment]
Thanks! Tried it out and it works. This wasn't blocking me on anything, it just seemed like it could be confusing.

**Comment by sagiegurari** [comment]
thanks for the feedback
