### ISSUE TITLE
Errors in `if` can lead to very surprising results.

### ISSUE THREAD

**Issue by rustonaut** [sagiegurari/duckscript#193]
### Describe The Bug

If you don't explicitly set `exit_on_failure true` then errors in the `if` condition can lead to both the `if` and `else` branch to be evaluated which I think should never happen.. Even with `exit_on_failure false`.

### To Reproduce

Be aware that there is a typo in the `greater_than` leading to an error.

```duckscript
if greater_then 2 1
    echo yes
else
    echo no
fi
```

Prints

```
yes
no
```

# Expected behavior

I'm not sure, I guess acting as if the condition failed (ah I mean was `false`).

Tbh. I was generally surprised that `exit_on_error` defaults to `false` and that
something which I would say is a "fatal error" doesn't print out any warning.

As well as that

**Comment by sagiegurari** [comment]
@rustonaut ok, i looked at the code and things came back to me.
so if does one of the following (from https://github.com/sagiegurari/duckscript/blob/master/docs/sdk.md#std__flowcontrol__If):

* A command with optional arguments and invokes it
* A single value which doesn't match any known command
* A condition statement

the first arg you gave is not a known command, so it is considered as a value.
however, you gave 2 args, so it doesn't match bullet 2 or 3 (condition statement is values with and/or....).
so the if fails as its just invalid input.
since errors by default do not break, it continues to next line, prints yes.
it than goes to the 'else'. however the else is also a command on its own and it sees its not invoked as part of an if/else block (because if failed to execute), so again, it just continues on.

so far the 'if' handling seems right to be, but the 'else' is something i need to think about.
reason is, that you can also goto directly into the else block and it would be ok, and when you hit an 'end' command, it will also ignore it. it makes sense since you can move to whereever at any point in the script.
it definitely feels strange and hard to debug at first, but it is due to the face that there are no real blocks in duckscript.

as for errors being silent, i actually put an example in the examples directory to make it echo
https://github.com/sagiegurari/duckscript/blob/master/examples/on_error_2.ds
so you can try that. but you can do even more smarter things if you really want.

i'm closing it for now, because although its confusing at first, you need to remember that if doesn't know how to differentiate between a command with spelling mistake and an actual text.
